nome = input('Qual é o seu nome?')
idade = input('Qual é sua idade?')
peso = input('Qual é o seu peso?')
print('Olá,', nome)
print('Vi que seu peso é', peso,'kg')
print('E que tem', idade,'anos')
print('Obrigado')