n = float(input('Digite o valor em metros para converter: '))
print('Convertendo {}m...'.format(n))
print('Em Decímetros: {:.0f}dm'.format(n*10))
print('Em Centímetros: {:.0f}cm'.format(n*100))
print('Em Milímetros: {:.0f}mm'.format(n*1000))
print('E também para...')
print('Em Decâmetros: {}dam'.format(n/10))
print('Em Hectômetros: {}hm'.format(n/100))
print('Em Kilômetros: {}km'.format(n/1000))