tx = input('Digite algo para verificação: ')
print('Analisando...')
print('OK')
print('O que você digitou é:')
print('Alfanumérico:',tx.isalnum())
print('Possui Letras:',tx.isalpha())
print('Possui Números:',tx.isnumeric())
print('Está em Maiúsculo:',tx.isupper())
print('Está em Minúsculo:',tx.islower())
print('É um Espaço:',tx.isspace())
print('Sua classe é:',type(tx))